// packages/angular/src/lib/ActiveList/ActiveList.component.ts
import {
  Component,
  ContentChild,
  OnInit,
  TemplateRef,
  Input,
} from '@angular/core';
import { ActiveListDirective } from './ActiveList.directive';
import { ActiveList, ActiveListConfig } from '@uiloos/core';

/**
 * A component which wraps the ActiveList from @uiloos/core.
 *  
 * @alias uiloos-active-list
 * @since 1.0.0
 * 
 * @example
 * 
 * A. Simple example
 * 
 * Uses the "<uiloos-active-list />" component together with the
 * "*uiloosActiveList" directive to create  a list with three items:
 *  a, b and c of which only one item can be active. Clicking an 
 * item makes it active.
 * 
 * ```html
 * <uiloos-active-list 
 *   [config]="{ 
 *     active: 'a', 
 *     contents: ['a', 'b', 'c']
 *   }"
 * >
 *   <ul *uiloosActiveList="let activeList">
 *     <li
 *       *ngFor="let content of activeList.contents"
 *       (click)="content.activate()"
 *     >
 *       {{content.value}} 
 *       {{content.isActive ? 'active' : 'inactive'}}
 *     </li>
 *   </ul>
 * </uiloos-active-list>
 * ```
 */
@Component({
  selector: 'uiloos-active-list',
  template: `
    <ng-container
      *ngTemplateOutlet="
        uiloosActiveList;
        context: { $implicit: activeList }
      "
    ></ng-container>
  `,
})
export class ActiveListComponent<T> implements OnInit {
  /**
   * An reference to the ActiveListDirective.
   * 
   * @since 1.0.0
   */
  @ContentChild(ActiveListDirective, { read: TemplateRef })
  public uiloosActiveList: any;

  /**
   * An `@Input` for the initial configuration of the ActiveList.
   * 
   * @since 1.0.0
   */
  @Input()
  public config!: ActiveListConfig<T>;

   /**
   * The exposed ActiveList.
   * 
   * @since 1.0.0
   */
  public activeList!: ActiveList<T>;

  ngOnInit(): void {
    this.activeList = new ActiveList(this.config);;
  }
}

// packages/react/src/ActiveList/ActiveList.tsx
import React, { ReactNode } from 'react';

import {
  ActiveList as ActiveListCore,
  ActiveListConfig,
} from '@uiloos/core';
import { useActiveList } from './useActiveList';

/**
 * The properties for the ActiveList React component.
 * 
 * It has all properties the ActiveListConfig has, plus a 
 * `children` property which is a render function which is given the
 * current ActiveList state to render.
 * 
 * @since 1.0.0
 */
export type ActiveListProps<T> = ActiveListConfig<T> & {

  /**
   * A render function which accepts an ActiveList from @uiloos/core
   * as a parameter.
   * 
   * @param {ActiveListCore<T>} activeContent The ActiveList from @uiloos/core
   * 
   * @since 1.0.0
   */
  children(activeContent: ActiveListCore<T>): ReactNode;
};

/**
 * A component which wraps the ActiveList from @uiloos/core.
 * 
 * @example
 * A. Simple example
 * 
 * The example below creates a list with three items: 
 * a, b and c of which only one item can be active. 
 * Clicking an item makes it active.
 * 
 * ```jsx
 * <ActiveList 
 *   active="a" 
 *   contents={['a', 'b', 'c']}
 * >
 *   {(activeContent) => (
 *     <ul>
 *       {activeContent.contents.map((content) => (
 *         <li 
 *           key={content.value} 
 *           onClick={() => content.activate()}
 *         >
 *           {content.value} 
 *           {content.isActive ? 'active' : 'inactive'}
 *         </li>
 *       ))}
 *     </ul>
 *   )}
 * </ActiveList>
 * ```
 * 
 * @param {ActiveListProps<T>} props The properties of the ActiveList component.
 * @returns A component which wraps the ActiveList from @uiloos/core.
 * 
 * @since 1.0.0
 */
export function ActiveList<T>(props: ActiveListProps<T>): JSX.Element {
  const activeContent = useActiveList(props);

  return <>{props.children(activeContent)}</>;
}
